### ISSUE TITLE
Daily check-in and code reedm not working

### ISSUE THREAD

**Issue by KEKKO96** [nano-shino/genshinhelper#11]

**Comment by nano-shino** [comment]
I use it every day and its working for me
![image](https://github.com/nano-shino/genshinhelper/assets/34665904/1bf76fe6-d79c-468b-9ed8-2bd5c3f49f27)

**Comment by KEKKO96** [comment]
> I use it every day and its working for me ![image](https://user-images.githubusercontent.com/34665904/282229446-1bf76fe6-d79c-468b-9ed8-2bd5c3f49f27.png) 
![image](https://github.com/nano-shino/genshinhelper/assets/35418939/d90aa1bb-9b21-4e73-8cb8-ee027213f27a)


I may have found the issue, I deleted my user and created a new one, but is now giving an error about invalid cookies
![image](https://github.com/nano-shino/genshinhelper/assets/35418939/117d62c4-4e97-4c99-9c2d-1b4460c6b643)

it works if instead of the "ltoken_v2" I use the "cookie_token_v2" but the automatic check-in does not work.

**Comment by nano-shino** [comment]
Please recheck your input and your bot setup. I have tested with a separate account and confirmed checkin/redeem both work. Closing this ticket
