### ISSUE TITLE
Add support for Zenless Zone Zero

### ISSUE THREAD

**Issue by KEKKO96** [nano-shino/genshinhelper#14]
Hi, could you add support for Zenless Zone Zero since it's there for Honkai impact 3rd? Thanks.
Also the bot doesn't redeem the rewards for Honkai Impact 3rd, I've tried logging back in but it didn't work.

**Comment by nano-shino** [comment]
Yes, ZZZ is on my todo list. Probably will get it done this weekend

**Comment by nano-shino** [comment]
also the bot supports genshin and HSR, not HI3

**Comment by KEKKO96** [comment]
Weird because for some months it worked fine for HI3

**Comment by nano-shino** [comment]
Oh I see why it worked. The default config didn't have honkai 3rd but you could still add it. I didn't try so I didn't think it would work
